In [6]:
import numpy as np
a=np.arange(24)
b=a.reshape(2,3,4)
print(b)
print(b.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3


In [7]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [12]:
a=np.array([1,2,3],dtype=np.int8)
print(a.itemsize)
print(a.flags)
print(a.imag)

1
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

[0 0 0]
