In [2]:
import numpy as np
x=np.empty([2,3],dtype=np.int)
print(x)

[[1969450820 1953391981 1851859059]
 [1699946596 1852404852 1012691815]]


In [3]:
a=np.zeros([3,3],dtype=np.float)
print(a)
b=np.ones([3,3],dtype=np.int)
print(b)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
