In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3])
print(a)
a=np.array([[1,2],[3,4]])
print(a)

[1 2 3]
[[1 2]
 [3 4]]


In [9]:
a=np.array([1,2,3],ndmin=2)
print(a)


[[1 2 3]]


In [11]:
a=np.array([1,2,3],dtype=complex)
print(a)


[1.+0.j 2.+0.j 3.+0.j]
